export const mockContent = [
  {
    id: "1",
    title: "Nueva Beca Internacional",
    type: "opportunity",
    status: "published",
    author: "María González",
    createdAt: "2024-03-15",
  },
  {
    id: "2",
    title: "Guía para Estudiar en el Extranjero",
    type: "blog",
    status: "draft",
    author: "Carlos Rodríguez",
    createdAt: "2024-03-14",
  },
  {
    id: "3",
    title: "Conferencia de Educación 2024",
    type: "news",
    status: "published",
    author: "Ana Martínez",
    createdAt: "2024-03-13",
  },
  {
    id: "4",
    title: "Beca Fulbright 2024",
    type: "opportunity",
    status: "published",
    author: "María González",
    createdAt: "2024-03-12",
  },
  {
    id: "5",
    title: "Tips para el TOEFL",
    type: "blog",
    status: "published",
    author: "Carlos Rodríguez",
    createdAt: "2024-03-11",
  },
  {
    id: "6",
    title: "Programa de Intercambio - España",
    type: "opportunity",
    status: "draft",
    author: "Ana Martínez",
    createdAt: "2024-03-10",
  },
  {
    id: "7",
    title: "Feria Virtual de Universidades",
    type: "news",
    status: "published",
    author: "María González",
    createdAt: "2024-03-09",
  },
  {
    id: "8",
    title: "Cómo Financiar tus Estudios",
    type: "blog",
    status: "published",
    author: "Carlos Rodríguez",
    createdAt: "2024-03-08",
  },
  {
    id: "9",
    title: "Becas para Latinoamérica 2024",
    type: "opportunity",
    status: "published",
    author: "Ana Martínez",
    createdAt: "2024-03-07",
  },
  {
    id: "10",
    title: "Workshop de Liderazgo",
    type: "news",
    status: "draft",
    author: "María González",
    createdAt: "2024-03-06",
  },
  {
    id: "11",
    title: "Experiencias de Estudiantes en el Extranjero",
    type: "blog",
    status: "published",
    author: "Carlos Rodríguez",
    createdAt: "2024-03-05",
  },
  {
    id: "12",
    title: "Beca para Estudios en Canadá",
    type: "opportunity",
    status: "published",
    author: "Ana Martínez",
    createdAt: "2024-03-04",
  },
  {
    id: "13",
    title: "Curso Gratuito de Idiomas",
    type: "opportunity",
    status: "draft",
    author: "María González",
    createdAt: "2024-03-03",
  },
];

export const mockUsers = [
  {
    id: "1",
    name: "María González",
    email: "maria@example.com",
    role: "Admin",
    status: "active",
    lastLogin: "2024-03-15 10:30",
  },
  {
    id: "2",
    name: "Carlos Rodríguez",
    email: "carlos@example.com",
    role: "Editor",
    status: "active",
    lastLogin: "2024-03-14 15:45",
  },
  {
    id: "3",
    name: "Ana Martínez",
    email: "ana@example.com",
    role: "User",
    status: "inactive",
    lastLogin: "2024-03-10 09:15",
  },
];
